### ISSUE TITLE
dari mana datangnya nilai perolehan suara disetiap Paslon?

### ISSUE THREAD

**Issue by muzalx** [razanfawwaz/pilkada-scrap#1]
Data scrapping nya memang betul yang diambil dari website KPU adalah data paslon, data province, data district dan data progress. Tapi yang memiliki nilai hanyalah data data yang diatas, sedangkan dari Web KPU nya sendiri tidak membeberkan nilai perolehan suara disetiap paslon nya.. Apakah scrapping ini hanyalah sebuah prediksi atau real ? jikalau itu real, data disetiap paslon diolah oleh admin @razanfawwaz? mohon penjelasannya bung. Data scrapping ini udah saya coba di local namun hasil perlolehan suara disetiap paslon memiliki nilai 0 sesuai scrapping dari Web KPU sendiri.

Data dari web KPU
![exmple data kpuwebscrap](https://github.com/user-attachments/assets/054a3a25-ad9f-4a92-aec1-12ef56905b6f)

Hasil data yang saya coba dari script bung @razanfawwaz di local
![local](https://github.com/user-attachments/assets/3e3b3631-b3e6-4f63-9dcd-88147725cecd)

**Comment by razanfawwaz** [comment]
halo mas, saat data yang di repo ini discrapping, kpu masih menampilkan data angka setiap paslon. namun mulai sekitar jam 10.45/11 pagi tadi data angka setiap paslon sudah dimatikan sepertinya sehingga hasil seperti yang bisa dilihat sekarang. oleh karena itu data di web visualisasi stuck dan menggunakan data terakhir yang saya scrapping di 10.15.

**Comment by ekosuhartono** [comment]
iya bener, visualisasi datanya stuck... -_-

**Comment by Rey1098-stuck** [comment]
Bukankah sebelum-sebelumnya memang tidak menampilkan data dalam bentuk angka ? Karena sebelumnya (pada tanggal 27 malam jam 9) saya cek tidak ada data berupa angka.

**Comment by muzalx** [comment]
> Bukankah sebelum-sebelumnya memang tidak menampilkan data dalam bentuk angka ? Karena sebelumnya (pada tanggal 27 malam jam 9) saya cek tidak ada data berupa angka.

Ada buktinya gak bang?

**Comment by ekosuhartono** [comment]
> Bukankah sebelum-sebelumnya memang tidak menampilkan data dalam bentuk angka ? Karena sebelumnya (pada tanggal 27 malam jam 9) saya cek tidak ada data berupa angka.

hanya sesama programmer yg faham akan hal ini ;-)

**Comment by asoka888** [comment]
kira2 ada kemungkinan bisa lagi gak ini kalau stuck begini

**Comment by neoBedjo** [comment]
> halo mas, saat data yang di repo ini discrapping, kpu masih menampilkan data angka setiap paslon. namun mulai sekitar jam 10.45/11 pagi tadi data angka setiap paslon sudah dimatikan sepertinya sehingga hasil seperti yang bisa dilihat sekarang. oleh karena itu data di web visualisasi stuck dan menggunakan data terakhir yang saya scrapping di 10.15.

Angka setiap paslon hilang, setelah abang rilis script scraping nya ke publik kah? Atau sebelum nya sumber data real time di web rekap yang abang buat itu langsung ambil referensi data ke api nya kpu? Jika iya. Kemungkinan besar karena tinggi nya traffic ke server kpu. Kpu memutuskan untuk mengosongkan data, agar traffic publik ke server nya turun.

**Comment by asoka888** [comment]
Apa kah kemungkinan bisa normal lagi

Pada Jum, 29 Nov 2024 08.51, neoBedjo ***@***.***> menulis:

**Comment by razanfawwaz** [comment]
> > halo mas, saat data yang di repo ini discrapping, kpu masih menampilkan data angka setiap paslon. namun mulai sekitar jam 10.45/11 pagi tadi data angka setiap paslon sudah dimatikan sepertinya sehingga hasil seperti yang bisa dilihat sekarang. oleh karena itu data di web visualisasi stuck dan menggunakan data terakhir yang saya scrapping di 10.15.
> 
> Angka setiap paslon hilang, setelah abang rilis script scraping nya ke publik kah? Atau sebelum nya sumber data real time di web rekap yang abang buat itu langsung ambil referensi data ke api nya kpu? Jika iya. Kemungkinan besar karena tinggi nya traffic ke server kpu. Kpu memutuskan untuk mengosongkan data, agar traffic publik ke server nya turun.

sebelumnya sumbernya real time langsung hit api kpu, namun saya sempat bikin script untuk coba scrapping. setelah angkanya hilang akhirnya saya pakai hasil scrapping

**Comment by neoBedjo** [comment]
> > > halo mas, saat data yang di repo ini discrapping, kpu masih menampilkan data angka setiap paslon. namun mulai sekitar jam 10.45/11 pagi tadi data angka setiap paslon sudah dimatikan sepertinya sehingga hasil seperti yang bisa dilihat sekarang. oleh karena itu data di web visualisasi stuck dan menggunakan data terakhir yang saya scrapping di 10.15.
> > 
> > 
> > Angka setiap paslon hilang, setelah abang rilis script scraping nya ke publik kah? Atau sebelum nya sumber data real time di web rekap yang abang buat itu langsung ambil referensi data ke api nya kpu? Jika iya. Kemungkinan besar karena tinggi nya traffic ke server kpu. Kpu memutuskan untuk mengosongkan data, agar traffic publik ke server nya turun.
> 
> sebelumnya sumbernya real time langsung hit api kpu, namun saya sempat bikin script untuk coba scrapping. setelah angkanya hilang akhirnya saya pakai hasil scrapping

Kemungkinan, penyebab kpu kosongkan data pasangan calon. Karena abang hit api kpu langsung, dan web yang abang buat viral, banyak yang buka, dan akhirnya bikin server punya beban yang bikin teknisi nya hapus data tiap calon kepala daerah.

**Comment by asoka888** [comment]
> > > halo mas, saat data yang di repo ini discrapping, kpu masih menampilkan data angka setiap paslon. namun mulai sekitar jam 10.45/11 pagi tadi data angka setiap paslon sudah dimatikan sepertinya sehingga hasil seperti yang bisa dilihat sekarang. oleh karena itu data di web visualisasi stuck dan menggunakan data terakhir yang saya scrapping di 10.15.
> > 
> > 
> > Angka setiap paslon hilang, setelah abang rilis script scraping nya ke publik kah? Atau sebelum nya sumber data real time di web rekap yang abang buat itu langsung ambil referensi data ke api nya kpu? Jika iya. Kemungkinan besar karena tinggi nya traffic ke server kpu. Kpu memutuskan untuk mengosongkan data, agar traffic publik ke server nya turun.
> 
> sebelumnya sumbernya real time langsung hit api kpu, namun saya sempat bikin script untuk coba scrapping. setelah angkanya hilang akhirnya saya pakai hasil scrapping

kira2 apa akan normal lagi

**Comment by razanfawwaz** [comment]
> > > > halo mas, saat data yang di repo ini discrapping, kpu masih menampilkan data angka setiap paslon. namun mulai sekitar jam 10.45/11 pagi tadi data angka setiap paslon sudah dimatikan sepertinya sehingga hasil seperti yang bisa dilihat sekarang. oleh karena itu data di web visualisasi stuck dan menggunakan data terakhir yang saya scrapping di 10.15.
> > > 
> > > 
> > > Angka setiap paslon hilang, setelah abang rilis script scraping nya ke publik kah? Atau sebelum nya sumber data real time di web rekap yang abang buat itu langsung ambil referensi data ke api nya kpu? Jika iya. Kemungkinan besar karena tinggi nya traffic ke server kpu. Kpu memutuskan untuk mengosongkan data, agar traffic publik ke server nya turun.
> > 
> > 
> > sebelumnya sumbernya real time langsung hit api kpu, namun saya sempat bikin script untuk coba scrapping. setelah angkanya hilang akhirnya saya pakai hasil scrapping
> 
> kira2 apa akan normal lagi

kecil kemungkinan, karena datanya angkanya sudah ditutup jadi akan terus menggunakan data terakhir seperti yang ditampilkan saat ini

**Comment by asoka888** [comment]
> > > > > halo mas, saat data yang di repo ini discrapping, kpu masih menampilkan data angka setiap paslon. namun mulai sekitar jam 10.45/11 pagi tadi data angka setiap paslon sudah dimatikan sepertinya sehingga hasil seperti yang bisa dilihat sekarang. oleh karena itu data di web visualisasi stuck dan menggunakan data terakhir yang saya scrapping di 10.15.
> > > > 
> > > > 
> > > > Angka setiap paslon hilang, setelah abang rilis script scraping nya ke publik kah? Atau sebelum nya sumber data real time di web rekap yang abang buat itu langsung ambil referensi data ke api nya kpu? Jika iya. Kemungkinan besar karena tinggi nya traffic ke server kpu. Kpu memutuskan untuk mengosongkan data, agar traffic publik ke server nya turun.
> > > 
> > > 
> > > sebelumnya sumbernya real time langsung hit api kpu, namun saya sempat bikin script untuk coba scrapping. setelah angkanya hilang akhirnya saya pakai hasil scrapping
> > 
> > 
> > kira2 apa akan normal lagi
> 
> kecil kemungkinan, karena datanya angkanya sudah ditutup jadi akan terus menggunakan data terakhir seperti yang ditampilkan saat ini

sangat di sayangkan sekali klo kecil kemungkinan atai tidak ada cara lain untuk hal tsb
