### ISSUE TITLE
Transparansi

### ISSUE THREAD

**Issue by Ak84rDark** [razanfawwaz/pilkada-scrap#2]
Kenapa hasil rekapitulasi penghitungan suara yang masuk tidak menyertakan suara tidak sah agar lebih transparan dan akurat.

**Comment by razanfawwaz** [comment]
dari endpoint yang didapatkan memang tidak ada kolom tersebut :) jadi sudah dalam bentuk total per pasangan

**Comment by Kakapimen** [comment]
Bang kapan bisa normal lagi ya.. soalnya dari kemarin masih mengalami stuck..

**Comment by razanfawwaz** [comment]
> Bang kapan bisa normal lagi ya.. soalnya dari kemarin masih mengalami stuck..

kecil kemungkinan, karena datanya angkanya sudah ditutup jadi akan terus menggunakan data terakhir seperti yang ditampilkan saat ini
